
#define EE_CAN_RESET_CNT	0x06
#define RESET_CNT	0x08

#define SECTOR_TOUCH_CALIBRATE 			0x10
#define SECTOR_KOEF 					0x100
#define SECTOR_EVENT_LOG				0x300

#define EE_CALIBRATION_IS_COMPLETE		SECTOR_TOUCH_CALIBRATE
#define EE_CALIBRATION_IS_ENOUG			SECTOR_TOUCH_CALIBRATE+2
#define EE_REG_TOUCH_TRANSFORM_A		SECTOR_TOUCH_CALIBRATE+4
#define EE_REG_TOUCH_TRANSFORM_B 		SECTOR_TOUCH_CALIBRATE+8
#define EE_REG_TOUCH_TRANSFORM_C		SECTOR_TOUCH_CALIBRATE+12
#define EE_REG_TOUCH_TRANSFORM_D  		SECTOR_TOUCH_CALIBRATE+16
#define EE_REG_TOUCH_TRANSFORM_E		SECTOR_TOUCH_CALIBRATE+20
#define EE_REG_TOUCH_TRANSFORM_F		SECTOR_TOUCH_CALIBRATE+24

#define EVENT_LOG						SECTOR_EVENT_LOG

